Add x-requested-with header to tile policy
openstreetmap/owg-website pull request #87
Opened 2022-07-15 01:47 UTC by pnorman

Opened for review via circular.

Fixes https://github.com/openstreetmap/operations/issues/663

2022-07-15 06:06 UTC, tomhughes approved these changes

2022-08-01 14:50 UTC, Firefishy commented
Maybe instead of:
> Sending an X-Requested-With header identifying application is acceptable, but not preferred.`

something like:

> If the device automatically sends an X-Requested-With header with an application specific Application ID, this will be considered an acceptable substitute for the HTTP User-Agent, although we still recommend setting a valid HTTP User-Agent.

2022-08-01 14:51 UTC, Firefishy requested changes
`If the device automatically sends an X-Requested-With header with an application specific Application ID, this will be considered an acceptable substitute for the HTTP User-Agent, although we still recommend setting a valid HTTP User-Agent.`

2022-08-03 03:59 UTC, pnorman commented
Updated language, with some minor grammar changes

2022-08-03 10:38 UTC, Firefishy approved these changes

2022-08-03 10:38 UTC, merged